using UnityEngine;
using EchoThief.Core;

namespace EchoThief.Player
{
    /// <summary>
    /// Handles player movement (sneak/run), ping input, and throwing.
    /// Uses Unity's new Input System via PlayerInput component (or legacy Input for prototyping).
    /// 
    /// Required Components: Rigidbody (or Rigidbody2D), NoiseEmitter, Collider.
    /// </summary>
    [RequireComponent(typeof(Rigidbody))]
    public class PlayerController : MonoBehaviour
    {
        [Header("Movement")]
        [SerializeField] private float _sneakSpeed = 3f;
        [SerializeField] private float _runSpeed = 7f;

        [Header("Ping")]
        [SerializeField] private float _pingCooldown = 1.5f;
        [SerializeField] private float _pingRadius = 10f;
        [SerializeField] private Color _pingColor = new Color(0f, 0.9f, 1f, 1f); // Cyan

        [Header("Running Sonar")]
        [Tooltip("Sonar radius generated by running footsteps.")]
        [SerializeField] private float _runSonarRadius = 6f;
        [Tooltip("How often running emits a sonar pulse (seconds).")]
        [SerializeField] private float _runPulseInterval = 0.4f;
        [SerializeField] private Color _runColor = new Color(0.16f, 0.47f, 1f, 1f); // Blue

        [Header("Throw")]
        [Tooltip("Prefab for the throwable noise maker.")]
        [SerializeField] private GameObject _noiseMakerPrefab;
        [SerializeField] private float _throwForce = 15f;
        [SerializeField] private int _noiseMakerCount = 3;

        private Rigidbody _rb;
        private NoiseEmitter _noiseEmitter;

        private Vector3 _moveInput;
        private Vector3 _lastMoveDir = Vector3.forward; // tracks last non-zero direction for throw
        private bool _isRunning;
        private float _pingTimer;
        private float _runPulseTimer;

        public int NoiseMakerCount => _noiseMakerCount;
        public float PingCooldownNormalized => Mathf.Clamp01(_pingTimer / _pingCooldown);
        public bool CanPing => _pingTimer <= 0f;

        private void Awake()
        {
            _rb = GetComponent<Rigidbody>();
            _noiseEmitter = GetComponent<NoiseEmitter>();

            if (_noiseEmitter == null)
            {
                _noiseEmitter = gameObject.AddComponent<NoiseEmitter>();
            }

            // Freeze rotation so physics don't tip us over
            _rb.freezeRotation = true;
        }

        private void Update()
        {
            // -- Input (legacy Input for prototyping — swap to new InputSystem later) --
            float h = Input.GetAxisRaw("Horizontal");
            float v = Input.GetAxisRaw("Vertical");
            _moveInput = new Vector3(h, 0f, v).normalized;

            // Track last non-zero direction so throw always goes the right way
            if (_moveInput.magnitude > 0.1f)
                _lastMoveDir = _moveInput;

            _isRunning = Input.GetKey(KeyCode.LeftShift) && _moveInput.magnitude > 0.1f;

            // Ping
            _pingTimer -= Time.deltaTime;
            if (Input.GetKeyDown(KeyCode.Space) && _pingTimer <= 0f)
            {
                Ping();
            }

            // Throw noise maker
            if (Input.GetKeyDown(KeyCode.E) && _noiseMakerCount > 0)
            {
                ThrowNoiseMaker();
            }

            // Running sonar pulses
            if (_isRunning)
            {
                _runPulseTimer -= Time.deltaTime;
                if (_runPulseTimer <= 0f)
                {
                    EmitRunPulse();
                    _runPulseTimer = _runPulseInterval;
                }
            }
            else
            {
                _runPulseTimer = 0f;
            }
        }

        private void FixedUpdate()
        {
            float speed = _isRunning ? _runSpeed : _sneakSpeed;
            Vector3 velocity = _moveInput * speed;
            velocity.y = _rb.linearVelocity.y; // preserve gravity
            _rb.linearVelocity = velocity;
        }

        /// <summary>
        /// Emit a sonar ping (clap). Medium noise, medium radius.
        /// </summary>
        private void Ping()
        {
            _pingTimer = _pingCooldown;

            NoiseEventBus.EmitNoise(new NoiseEvent(
                origin: transform.position,
                loudness: 0.5f,
                sonarRadius: _pingRadius,
                sonarColor: _pingColor,
                source: gameObject
            ));

            // Track for scoring
            if (ScoreManager.Instance != null)
                ScoreManager.Instance.AddPing();

            Debug.Log("[Player] Ping!");
        }

        /// <summary>
        /// Emit a small sonar pulse from running footsteps.
        /// </summary>
        private void EmitRunPulse()
        {
            NoiseEventBus.EmitNoise(new NoiseEvent(
                origin: transform.position,
                loudness: 0.7f,
                sonarRadius: _runSonarRadius,
                sonarColor: _runColor,
                source: gameObject
            ));
        }

        /// <summary>
        /// Throw a noise maker in the direction the player is facing.
        /// </summary>
        private void ThrowNoiseMaker()
        {
            if (_noiseMakerPrefab == null)
            {
                Debug.LogWarning("[Player] NoiseMaker prefab not assigned!");
                return;
            }

            _noiseMakerCount--;

            // Use current input if moving, otherwise use last known direction
            Vector3 throwDir = _moveInput.magnitude > 0.1f ? _moveInput : _lastMoveDir;
            Vector3 spawnPos = transform.position + throwDir * 1f + Vector3.up * 0.5f;

            GameObject noiseMaker = Object.Instantiate(_noiseMakerPrefab, spawnPos, Quaternion.identity);
            Rigidbody nmRb = noiseMaker.GetComponent<Rigidbody>();
            if (nmRb != null)
            {
                nmRb.AddForce(throwDir * _throwForce, ForceMode.Impulse);
            }

            Debug.Log($"[Player] Threw noise maker! Remaining: {_noiseMakerCount}");
        }

        /// <summary>
        /// Add noise makers to inventory.
        /// </summary>
        public void AddNoiseMaker(int amount)
        {
            _noiseMakerCount += amount;
            Debug.Log($"[Player] Picked up {amount} Noise Maker(s). Total: {_noiseMakerCount}");
        }
    }
}
